Page:
  in: query
  name: page
  type: integer
  description: 'Page # in the collection'

ItemsPerPage:
  in: query
  name: itemsPerPage
  type: integer
  description: How many documents per page?

SortBy:
  in: query
  name: sortBy
  type: string
  description: By which fields to sort?

Sort:
  in: query
  name: sort
  description: Sort by which order?
  schema:
    type: string
    enum: [
        ASC,
        DESC
      ]
    
SearchQuery:
  in: query
  name: q
  type: string 
  description: Search query content

ApiKeyHeader:
  in: header
  name: X-Api-Key
  schema:
    type: string
  required: true
  example: 5c29112cbb65c135bbe51179